language: php

php:
  - "7.1"

before_script:
  - composer install --no-interaction
  - php artisan key:generate

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master